//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 12:16:10 AM AEST 
//


package unico.assignment.soap.webservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the unico.assignment.soap.webservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: unico.assignment.soap.webservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGCDRequest }
     * 
     */
    public GetGCDRequest createGetGCDRequest() {
        return new GetGCDRequest();
    }

    /**
     * Create an instance of {@link GetGCDListResponse }
     * 
     */
    public GetGCDListResponse createGetGCDListResponse() {
        return new GetGCDListResponse();
    }

    /**
     * Create an instance of {@link GetGCDResponse }
     * 
     */
    public GetGCDResponse createGetGCDResponse() {
        return new GetGCDResponse();
    }

    /**
     * Create an instance of {@link GetGCDSumResponse }
     * 
     */
    public GetGCDSumResponse createGetGCDSumResponse() {
        return new GetGCDSumResponse();
    }

    /**
     * Create an instance of {@link GetGCDListRequest }
     * 
     */
    public GetGCDListRequest createGetGCDListRequest() {
        return new GetGCDListRequest();
    }

    /**
     * Create an instance of {@link GetGCDSumRequest }
     * 
     */
    public GetGCDSumRequest createGetGCDSumRequest() {
        return new GetGCDSumRequest();
    }

}
