//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.15 at 12:16:10 AM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://unico/assignment/soap/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package unico.assignment.soap.webservice;
